# Site settings
title: Joshua Lampman
description: Jekyll Theme Minimal Resume
# baseurl: "lampmanjosh.com" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joshua Lampman
user_description: Aspiring Cyber Security Professional
user_title: Pen-Test | <font color="red">Red</font>-Team
email: lampmanjosh@gmail.com
# twitter_username: lampmanjosh
# github_username:  lampmanjosh
# gplus_username:  lampmanjosh

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
